spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/filmlog
    username: seu_usuario
    password: sua_senha
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
